// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.djinni.android;

public abstract class TextboxListener {
    public abstract void update(ItemList items);
}
